import { BoardState } from '../../types/board';

export const BOARD_SEED: BoardState = {
  nodes: [
    {
      id: 'production-tail-plan',
      title: 'Production Tail Plan',
      body: 'Finalize assembly schedule and align with QA for end-of-week run.',
      dept: 'Production',
      owner: 'Amelia Rivers',
      ownerAvatar: 'AR',
      dueDate: '2024-05-18',
      status: 'Pending',
      x: -120,
      y: -40,
      color: '#F97316',
      history: [
        { id: 'h1', type: 'create', summary: 'Seeded node created', timestamp: Date.now() },
      ],
    },
    {
      id: 'finance-review',
      title: 'Finance Review',
      body: 'Verify budget coverage for change orders and capex allocation.',
      dept: 'Finance',
      owner: 'Liam Chen',
      ownerAvatar: 'LC',
      dueDate: '2024-05-16',
      status: 'Draft',
      x: 220,
      y: -120,
      color: '#6366F1',
      history: [
        { id: 'h2', type: 'create', summary: 'Seeded node created', timestamp: Date.now() },
      ],
    },
    {
      id: 'warehouse-prepare-batch',
      title: 'Warehouse Prepare Batch',
      body: 'Stage raw materials and confirm counts against ERP pick list.',
      dept: 'Warehouse',
      owner: 'Priya Das',
      ownerAvatar: 'PD',
      dueDate: '2024-05-17',
      status: 'Approved',
      x: -60,
      y: 220,
      color: '#14B8A6',
      history: [
        { id: 'h3', type: 'create', summary: 'Seeded node created', timestamp: Date.now() },
      ],
    },
    {
      id: 'logistics-schedule',
      title: 'Logistics Schedule',
      body: 'Lock carrier slots and issue pre-alert for interplant transfer.',
      dept: 'Logistics',
      owner: 'Diego Martins',
      ownerAvatar: 'DM',
      dueDate: '2024-05-19',
      status: 'Pending',
      x: 300,
      y: 200,
      color: '#0EA5E9',
      history: [
        { id: 'h4', type: 'create', summary: 'Seeded node created', timestamp: Date.now() },
      ],
    },
  ],
  edges: [
    {
      id: 'edge-budget',
      source: 'finance-review',
      target: 'production-tail-plan',
      label: 'Budget',
      type: 'dependency',
    },
    {
      id: 'edge-approve-release',
      source: 'production-tail-plan',
      target: 'warehouse-prepare-batch',
      label: 'Approve → Release',
      type: 'handoff',
    },
    {
      id: 'edge-transfer-doc',
      source: 'warehouse-prepare-batch',
      target: 'logistics-schedule',
      label: 'Transfer Doc',
      type: 'handoff',
    },
  ],
  viewport: {
    x: 0,
    y: 0,
    zoom: 1,
  },
  lastUpdated: Date.now(),
};
